--Q1
SELECT *
FROM CITY
WHERE COUNTRY_CODE = 'USA'
AND POPULATION > 100000;

-- Q2
SELECT NAME
FROM CITY
WHERE COUNTRY_CODE = 'USA'
AND POPULATION > 100000;


--Q3
SELECT *
FROM CITY;


--Q4
SELECT *
FROM CITY
WHERE ID = 1661;


--Q5
SELECT *
FROM CITY
WHERE COUNTRY_CODE = 'JPN';


--Q6
SELECT NAME
FROM CITY
WHERE COUNTRY_CODE = 'JPN';


--Q7
SELECT CITY, STATE
FROM STATION;


--Q8
SELECT DISTINCT CITY
FROM STATION
WHERE MOD(ID,2) = 0;



--Q9
SELECT t1.city_count - t2.distinct_city_count
FROM
(
SELECT COUNT(*) AS city_count
FROM STATION
) t1,
(
SELECT COUNT(*) AS distinct_city_count
FROM
(
    SELECT CITY, COUNT(STATE)
    FROM STATION
    GROUP BY CITY
) t3
) t2;



--Q10
WITH CTE AS
(
SELECT
    CITY
    , LENGTH(CITY) AS CITY_LEN
    , RANK() OVER (ORDER BY LENGTH(CITY) DESC, CITY DESC) AS UPPER_RANK
FROM STATION
ORDER BY UPPER_RANK DESC, CITY
)
SELECT CTE.CITY, CTE.CITY_LEN
FROM CTE
WHERE CTE.UPPER_RANK = (SELECT MAX(UPPER_RANK) FROM CTE)
OR CTE.UPPER_RANK = (SELECT MIN(UPPER_RANK) FROM CTE);


--Q11
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%'
ORDER BY CITY ASC;


--Q12
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u'
ORDER BY CITY ASC;


--Q13
SELECT DISTINCT CITY
FROM STATION
WHERE NOT(CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%')
ORDER BY CITY ASC;


--Q14
SELECT DISTINCT CITY
FROM STATION
WHERE NOT(CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u')
ORDER BY CITY ASC;


--Q15
SELECT DISTINCT CITY
FROM STATION
WHERE
NOT(CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%')
OR
NOT(CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u')
ORDER BY CITY;


--Q16
SELECT DISTINCT CITY
FROM STATION
WHERE
NOT(CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%')
AND
NOT(CITY LIKE '%a'
OR CITY LIKE '%e'
OR CITY LIKE '%i'
OR CITY LIKE '%o'
OR CITY LIKE '%u')
ORDER BY CITY;


--Q17
(
SELECT SALES.product_id, PRODUCT.product_name
FROM PRODUCT
JOIN SALES ON PRODUCT.product_id = SALES.product_id
WHERE TO_CHAR(SALES.sale_date, 'YYYY-MM-DD') BETWEEN '2019-01-01' AND '2019-03-31'
)
MINUS
(
SELECT SALES.product_id, PRODUCT.product_name
FROM PRODUCT
JOIN SALES ON PRODUCT.product_id = SALES.product_id
WHERE TO_CHAR(SALES.sale_date, 'YYYY-MM-DD') > '2019-03-31'
);



--Q18
SELECT DISTINCT AUTHOR_ID
FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY AUTHOR_ID;


--Q19
SELECT ROUND((t2.immediate_deliveries/t1.total_deliveries)*100, 2) AS immediate_percentage
FROM
(
    SELECT COUNT(*) AS total_deliveries
    FROM DELIVERY
) t1,
(
    SELECT COUNT(*) AS immediate_deliveries
    FROM DELIVERY
    WHERE ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE
) t2
;



--Q20
WITH CTE AS
(
SELECT t1.AD_ID, SUM(t1.clicked_viewed) AS total_clicks, COUNT(t1.clicked_viewed) AS total_views_and_clicks
FROM
(
SELECT
    AD_ID
    , ACTION
    ,CASE 
        WHEN ACTION = 'Clicked' THEN 1
        WHEN ACTION = 'Viewed' THEN 0
        WHEN ACTION = 'Ignored' THEN NULL
    END
    AS clicked_viewed
FROM ADS
) t1
GROUP BY t1.AD_ID
)
SELECT CTE.AD_ID, NVL(ROUND((CTE.total_clicks/CTE.total_views_and_clicks)*100, 2), 0) AS ctr
FROM CTE;



--Q21
SELECT Employee.employee_id, t1.team_size
FROM
(
SELECT team_id, COUNT(*) AS team_size
FROM Employee
GROUP BY team_id
) t1
JOIN Employee
ON t1.team_id = Employee.team_id;



--Q22
WITH CTE AS
(
SELECT Countries.country_id, Countries.country_name, AVG(Weather.weather_state) AS avg_weather
FROM Countries
JOIN Weather ON Countries.country_id = Weather.country_id
WHERE TO_CHAR(Weather.day, 'YYYY-MM-DD') BETWEEN '2019-11-01' AND '2019-11-30'
GROUP BY Countries.country_id, Countries.country_name
)
SELECT
    country_name
    , CASE
        WHEN avg_weather <= 15 THEN 'Cold'
        WHEN avg_weather >= 25 THEN 'Hot'
        ELSE 'Warm'
    END
    AS weather_type
FROM CTE;


--Q23












